MODEL:
  TYPE: fastpredNF_CIF_separate_cond_clusterGMM
  ENCODER_TYPE: trajectron

DATA:
  DATASET_NAME: "hotel"
  TP:
    PRED_STATE: 'state_v'
    ACCEPT_NAN: True
  BATCH_SIZE: 1024
  NORMALIZED: True
    
SOLVER:
  USE_SCHEDULER: True
  WEIGHT_DECAY: 0.0
  SAVE_EVERY: 1
  LR: 1e-3 
  ITER: 100

MGF:
  ENABLE: True
  CLUSTER_N: 7
  VAR_INIT: 0.3
  VAR_LEARNABLE: True
  POST_CLUSTER: 500