MODEL:
  TYPE: fastpredNF_CIF_separate_cond_clusterGMM
  ENCODER_TYPE: trajectron

DATA:
  DATASET_NAME: "zara1"
  TP:
    PRED_STATE: 'state_v'
    ACCEPT_NAN: True
  NORMALIZED: False
    
SOLVER:
  USE_SCHEDULER: True
  SAVE_EVERY: 1

MGF:
  ENABLE: True
  CLUSTER_N: 7
  VAR_INIT: 0.3
  VAR_LEARNABLE: True
  POST_CLUSTER: 500